### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by jeffantosh** [kirlut/AlphaVantage.Net#24]
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Error occured while parsing Technical Indicators response)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at StockAlgo0.Program.Main(String[] args) in C:\Users\antjef01\source\repos\StockAlgo0\StockAlgo0\Program.cs:line 31

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
AlphaVantageParsingException: Error occured while parsing Technical Indicators response

Inner Exception 2:
InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'String'.

Here's the API call I'm trying to make: https://www.alphavantage.co/query?function=ATR&symbol=SPCE&interval=weekly&time_period=20&apikey=APIKEYGOESHERE

Here's the code I'm using:
`
        public override async Task Execute(string ticker)
        {
            var query = new Dictionary<string, string>
                {
                    {"time_period", _timePeriod.ToString()},
                    {"series_type", "close"}
                };

            var result = await _client.GetTechIndicatorTimeSeriesAsync(ticker, TechIndicatorType.ATR, _setInterval, query);
         }
`

This seems to work fine for some stocks, but not others.
Working stocks: AAPL, PAVE
Non-Working stocks: SPCE, GDRX

**Comment by jeffantosh** [comment]
It seems to be affecting different tickers at different times, but it always seems to bomb out when I'm looping though a few tickers.

Here's the full code:
https://github.com/jeffantosh/StockAlgo0

**Comment by jeffantosh** [comment]
Update: I used Fidler to capture the traffic and found this response from AlphaVantage: "Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency."

Maybe this project should be updated to catch this and display a custom error instead of the parsing error I was seeing before. Take this as a suggestion, but I will close this ticket.

Thanks!
